# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/event_booking
spring.datasource.username=postgres
spring.datasource.password=postgresqlpassword

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=myVeryStrongSecretKeyForEventBookingSystem2026SpringBootJWT
app.jwt.expiration=86400000

# Server
server.port=8080